export enum LeagueMap {
  SUMMONERS_RIFT_SUMMER = 1,
  SUMMONERS_RIFT_AUTUMN = 2,
  THE_PROVING_GROUNDS = 3,
  TWISTED_TREELINE_ORIGINAL = 4,
  THE_CRYSTAL_SCAR = 8,
  TWISTED_TREELINE_CURRENT = 10,
  SUMMONERS_RIFT = 11,
  HOWLING_ABYSS = 12,
  BUTCHERS_BRIDGE = 14,
  COSMIC_RUINS = 16
}
