export class ParticipantStats {
  public physicalDamageDealt: number;
  public neutralMinionsKilledTeamJungle: number;
  public magicDamageDealt: number;
  public totalPlayerScore: number;
  public deaths: number;
  public win: boolean;
  public neutralMinionsKilledEnemyJungle: number;
  public altarsCaptured: number;
  public largestCriticalStrike: number;
  public totalDamageDealt: number;
  public magicDamageDealtToChampions: number;
  public visionWardsBoughtInGame: number;
  public damageDealtToObjectives: number;
  public largestKillingSpree: number;
  public item1: number;
  public quadraKills: number;
  public teamObjective: number;
  public totalTimeCrowdControlDealt: number;
  public numberestTimeSpentLiving: number;
  public wardsKilled: number;
  public firstTowerAssist: boolean;
  public firstTowerKill: boolean;
  public item2: number;
  public item3: number;
  public item0: number;
  public firstBloodAssist: boolean;
  public visionScore: number;
  public wardsPlaced: number;
  public item4: number;
  public item5: number;
  public item6: number;
  public turretKills: number;
  public tripleKills: number;
  public damageSelfMitigated: number;
  public champLevel: number;
  public nodeNeutralizeAssist: number;
  public firstInhibitorKill: boolean;
  public goldEarned: number;
  public magicalDamageTaken: number;
  public kills: number;
  public doubleKills: number;
  public nodeCaptureAssist: number;
  public trueDamageTaken: number;
  public nodeNeutralize: number;
  public firstInhibitorAssist: boolean;
  public assists: number;
  public unrealKills: number;
  public neutralMinionsKilled: number;
  public objectivePlayerScore: number;
  public combatPlayerScore: number;
  public damageDealtToTurrets: number;
  public altarsNeutralized: number;
  public physicalDamageDealtToChampions: number;
  public goldSpent: number;
  public trueDamageDealt: number;
  public trueDamageDealtToChampions: number;
  public participantId: number;
  public pentaKills: number;
  public totalHeal: number;
  public totalMinionsKilled: number;
  public firstBloodKill: boolean;
  public nodeCapture: number;
  public largestMultiKill: number;
  public sightWardsBoughtInGame: number;
  public totalDamageDealtToChampions: number;
  public totalUnitsHealed: number;
  public inhibitorKills: number;
  public totalScoreRank: number;
  public totalDamageTaken: number;
  public killingSprees: number;
  public timeCCingOthers: number;
  public physicalDamageTaken: number;

  constructor() {
    this.physicalDamageDealt = void 0;
    this.neutralMinionsKilledTeamJungle = void 0;
    this.magicDamageDealt = void 0;
    this.totalPlayerScore = void 0;
    this.deaths = void 0;
    this.win = void 0;
    this.neutralMinionsKilledEnemyJungle = void 0;
    this.altarsCaptured = void 0;
    this.largestCriticalStrike = void 0;
    this.totalDamageDealt = void 0;
    this.magicDamageDealtToChampions = void 0;
    this.visionWardsBoughtInGame = void 0;
    this.damageDealtToObjectives = void 0;
    this.largestKillingSpree = void 0;
    this.item1 = void 0;
    this.quadraKills = void 0;
    this.teamObjective = void 0;
    this.totalTimeCrowdControlDealt = void 0;
    this.numberestTimeSpentLiving = void 0;
    this.wardsKilled = void 0;
    this.firstTowerAssist = void 0;
    this.firstTowerKill = void 0;
    this.item2 = void 0;
    this.item3 = void 0;
    this.item0 = void 0;
    this.firstBloodAssist = void 0;
    this.visionScore = void 0;
    this.wardsPlaced = void 0;
    this.item4 = void 0;
    this.item5 = void 0;
    this.item6 = void 0;
    this.turretKills = void 0;
    this.tripleKills = void 0;
    this.damageSelfMitigated = void 0;
    this.champLevel = void 0;
    this.nodeNeutralizeAssist = void 0;
    this.firstInhibitorKill = void 0;
    this.goldEarned = void 0;
    this.magicalDamageTaken = void 0;
    this.kills = void 0;
    this.doubleKills = void 0;
    this.nodeCaptureAssist = void 0;
    this.trueDamageTaken = void 0;
    this.nodeNeutralize = void 0;
    this.firstInhibitorAssist = void 0;
    this.assists = void 0;
    this.unrealKills = void 0;
    this.neutralMinionsKilled = void 0;
    this.objectivePlayerScore = void 0;
    this.combatPlayerScore = void 0;
    this.damageDealtToTurrets = void 0;
    this.altarsNeutralized = void 0;
    this.physicalDamageDealtToChampions = void 0;
    this.goldSpent = void 0;
    this.trueDamageDealt = void 0;
    this.trueDamageDealtToChampions = void 0;
    this.participantId = void 0;
    this.pentaKills = void 0;
    this.totalHeal = void 0;
    this.totalMinionsKilled = void 0;
    this.firstBloodKill = void 0;
    this.nodeCapture = void 0;
    this.largestMultiKill = void 0;
    this.sightWardsBoughtInGame = void 0;
    this.totalDamageDealtToChampions = void 0;
    this.totalUnitsHealed = void 0;
    this.inhibitorKills = void 0;
    this.totalScoreRank = void 0;
    this.totalDamageTaken = void 0;
    this.killingSprees = void 0;
    this.timeCCingOthers = void 0;
    this.physicalDamageTaken = void 0;
  }
}